import type { Metadata } from 'next';
import { Cairo } from 'next/font/google';
import { AppProvider } from '@/components/providers/app-provider';
import './globals.css';
import Test from '@/components/test';

const cairo = Cairo({
  variable: '--font-cairo',
  subsets: ['arabic', 'latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body
        className={`${cairo.variable} font-(family-name:--font-cairo) antialiased`}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
